# -*- coding: utf-8 -*-
"""Visualization of statistical data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_9ZZrECzPcak0g2cwVSXCu_L8i2uskq
"""

# ANCOVA forest plot — Mora-Gonzalez et al. (2024), Supplementary Table S2
# Run in Google Colab. The PNG is downloaded automatically at the end.

import matplotlib.pyplot as plt
from matplotlib.transforms import blended_transform_factory

# ---------------- settings ----------------
FILENAME    = "ancova_forest_plot.png"
TRANSPARENT = True       # True = transparent background; False = white background
SHOW_NOTE   = True       # source note under the plot
DPI         = 300

# classic palette (colorblind-friendly Okabe-Ito blue/orange + neutral grays)
BG, BAND   = "#FFFFFF", "#EEEEEE"
TEXT, GRAY = "#222222", "#666666"
AXIS       = "#333333"
BLUE, GREEN, BROWN = "#0072B2", "#D55E00", "#555555"   # BLUE = DNMS, GREEN = Flanker

plt.rcParams["font.family"] = ["Calibri", "Carlito", "Liberation Sans", "DejaVu Sans"]

# ---------------- data (Table S2, z-score differences: exercise − control) ----------------
# Baseline-adjusted (ANCOVA). RT rows are sign-reversed so that right = better for the exercise group.
# (label, estimate, lower 95% CI, upper 95% CI, p)
groups = [
    ("DNMS  ·  working memory", BLUE, [
        ("Low load · RT",           -0.14, -0.53, 0.25, ".484"),
        ("Low load · accuracy",     -0.08, -0.51, 0.35, ".712"),
        ("High load · RT",           0.02, -0.44, 0.47, ".947"),
        ("High load · accuracy",    -0.06, -0.48, 0.36, ".791"),
    ]),
    ("Flanker  ·  inhibitory control", GREEN, [
        ("Congruent · RT",           0.00, -0.42, 0.42, ".998"),
        ("Congruent · accuracy",     0.09, -0.28, 0.46, ".625"),
        ("Incongruent · RT",        -0.08, -0.45, 0.28, ".647"),
        ("Incongruent · accuracy",   0.07, -0.13, 0.27, ".496"),
    ]),
]

# ---------------- layout: one y position per line, top to bottom ----------------
rows, y = [], 0.0
for header, color, items in groups:
    rows.append(("header", y, header, color, None)); y -= 1
    for item in items:
        rows.append(("item", y, item, color, None)); y -= 1
    y -= 0.25                                   # small gap between tasks
y_top, y_bottom = 0.5, y + 0.25 + 0.5           # plotting range

# ---------------- figure ----------------
fig, ax = plt.subplots(figsize=(4.4, 3.7), dpi=DPI)
fig.subplots_adjust(left=0.40, right=0.89, top=0.98, bottom=0.27 if SHOW_NOTE else 0.15)
if not TRANSPARENT:
    fig.patch.set_facecolor(BG); ax.set_facecolor(BG)

XMIN, XMAX = -0.6, 0.6
ax.set_xlim(XMIN, XMAX)
ax.set_ylim(y_bottom, y_top)

first_item_y = rows[1][1]
ax.axvspan(-0.2, 0.2, color=BAND, zorder=0, lw=0)                                      # < small effect
ax.plot([0, 0], [first_item_y + 0.5, y_bottom], color=GRAY, lw=0.8, ls=(0, (3, 2)), zorder=1)  # zero line

lab = blended_transform_factory(fig.transFigure, ax.transData)   # x in figure fraction, y in data
for kind, yy, payload, color, _ in rows:
    if kind == "header":
        ax.text(0.02, yy, payload, transform=lab, ha="left", va="center",
                fontsize=9.5, fontweight="bold", color=color)
        continue
    name, est, lo, hi, p = payload
    ax.text(0.05, yy, name, transform=lab, ha="left", va="center", fontsize=9.5, color=TEXT)
    ax.errorbar(est, yy, xerr=[[est - lo], [hi - est]], fmt="o", color=color, ecolor=color,
                elinewidth=1.6, capsize=3.2, capthick=1.6, markersize=6.5,
                markeredgecolor="white", markeredgewidth=0.8, zorder=3)
    ax.text(0.985, yy, p, transform=lab, ha="right", va="center", fontsize=9.5, color=TEXT)

# column labels on the first header row
ax.text(0.0, rows[0][1], "< 0.2 SD", ha="center", va="center", fontsize=8, style="italic", color=GRAY)
ax.text(0.985, rows[0][1], "p", transform=lab, ha="right", va="center",
        fontsize=9.5, style="italic", fontweight="bold", color=GRAY)

# axes styling
ax.set_yticks([])
for side in ("top", "right", "left"):
    ax.spines[side].set_visible(False)
ax.spines["bottom"].set_color(AXIS)
ax.spines["bottom"].set_linewidth(0.8)
ticks = [-0.6, -0.3, 0, 0.3, 0.6]
ax.set_xticks(ticks)
ax.set_xticklabels(["\u22120.6", "\u22120.3", "0", "+0.3", "+0.6"], fontsize=8.5, color=GRAY)
ax.tick_params(axis="x", colors=AXIS, labelcolor=GRAY, length=3, width=0.8)

# "favors" labels under the axis
ax.text(-0.03, -0.12, "\u2190 favors control", transform=blended_transform_factory(ax.transData, ax.transAxes),
        ha="right", va="top", fontsize=8.5, color=GRAY)
ax.text(0.03, -0.12, "favors exercise \u2192", transform=blended_transform_factory(ax.transData, ax.transAxes),
        ha="left", va="top", fontsize=8.5, color=GRAY)

if SHOW_NOTE:
    fig.text(0.02, 0.015,
             "Baseline-adjusted difference (exercise \u2212 control) in SD units, with 95% CI;\n"
             "RT sign reversed so right = better. Data: Mora-Gonzalez et al. (2024), Table S2.\n"
             "Figure created by the presenter from these data; not a figure from the original article.",
             ha="left", va="bottom", fontsize=7.5, style="italic", color=GRAY, linespacing=1.3)

fig.savefig(FILENAME, dpi=DPI, transparent=TRANSPARENT,
            facecolor="none" if TRANSPARENT else BG)
plt.show()

# ---------------- auto-download (goes to your Mac's Downloads folder) ----------------
try:
    from google.colab import files
    files.download(FILENAME)
except ImportError:
    print(f"Saved {FILENAME} (not running in Colab, so no auto-download).")

# z-score of change by group — Mora-Gonzalez et al. (2024), Supplementary Table S2
# Run in Google Colab. The PNG is downloaded automatically at the end.

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.transforms import blended_transform_factory

# ---------------- settings ----------------
FILENAME    = "zscore_change_plot.png"
TRANSPARENT = True       # True = transparent background; False = white background
SHOW_NOTE   = True       # source note under the plot
FLIP_RT     = True       # reverse RT sign so that right = better for every outcome
DPI         = 300

# classic palette (same as the ANCOVA forest plot)
BG, BAND   = "#FFFFFF", "#EEEEEE"
TEXT, GRAY = "#222222", "#666666"
AXIS       = "#333333"
BLUE, ORANGE = "#0072B2", "#D55E00"      # BLUE = DNMS, ORANGE = Flanker

plt.rcParams["font.family"] = ["Calibri", "Carlito", "Liberation Sans", "DejaVu Sans"]

# ---------------- data (Table S2, z-score of change, adjusted for baseline) ----------------
# (label, exercise z, ex lower, ex upper, control z, ctl lower, ctl upper) — values exactly as printed in Table S2
groups = [
    ("DNMS  ·  working memory", BLUE, [
        ("Low load · RT",          -0.33, -0.60, -0.07,   -0.47, -0.76, -0.19),
        ("Low load · accuracy",     0.10, -0.19,  0.39,    0.18, -0.13,  0.49),
        ("High load · RT",         -0.38, -0.69, -0.07,   -0.36, -0.70, -0.03),
        ("High load · accuracy",   -0.01, -0.30,  0.27,    0.04, -0.26,  0.35),
    ]),
    ("Flanker  ·  inhibitory control", ORANGE, [
        ("Congruent · RT",         -0.37, -0.66, -0.08,   -0.37, -0.68, -0.07),
        ("Congruent · accuracy",    0.19, -0.06,  0.44,    0.10, -0.17,  0.36),
        ("Incongruent · RT",       -0.40, -0.65, -0.14,   -0.48, -0.75, -0.22),
        ("Incongruent · accuracy",  0.33,  0.19,  0.47,    0.26,  0.12,  0.40),
    ]),
]


def oriented(label, est, lo, hi):
    """For RT, lower = faster = better. Flip the sign so right = better."""
    if FLIP_RT and "RT" in label:
        return -est, -hi, -lo
    return est, lo, hi


# ---------------- layout: one y position per line, top to bottom ----------------
rows, y = [], 0.0
for header, color, items in groups:
    rows.append(("header", y, header, color)); y -= 1
    for item in items:
        rows.append(("item", y, item, color)); y -= 1
    y -= 0.25
y_top, y_bottom = 0.95, y + 0.25 + 0.5

# ---------------- figure ----------------
fig, ax = plt.subplots(figsize=(4.4, 3.9), dpi=DPI)
fig.subplots_adjust(left=0.40, right=0.97, top=0.98, bottom=0.265 if SHOW_NOTE else 0.15)
if not TRANSPARENT:
    fig.patch.set_facecolor(BG); ax.set_facecolor(BG)

XMIN, XMAX = -0.4, 0.9
ax.set_xlim(XMIN, XMAX)
ax.set_ylim(y_bottom, y_top)

first_item_y = rows[1][1]
ax.axvspan(-0.2, 0.2, color=BAND, zorder=0, lw=0)                                  # < 0.2 SD = negligible
ax.plot([0, 0], [first_item_y + 0.5, y_bottom], color=GRAY, lw=0.8, zorder=1)      # zero = no change
for b, name in [(0.2, "small"), (0.5, "medium"), (0.8, "large")]:                  # effect-size benchmarks
    ax.plot([b, b], [first_item_y + 0.5, y_bottom], color=GRAY, lw=0.7, ls=(0, (1, 2)), zorder=1)
    ax.text(b, rows[0][1] + 0.55, name, ha="center", va="center", fontsize=7.5, style="italic", color=GRAY)

lab = blended_transform_factory(fig.transFigure, ax.transData)   # x in figure fraction, y in data
OFF = 0.18                                                       # vertical offset: exercise above, control below
for kind, yy, payload, color in rows:
    if kind == "header":
        ax.text(0.02, yy, payload, transform=lab, ha="left", va="center",
                fontsize=9.5, fontweight="bold", color=color)
        continue
    name, ex, ex_lo, ex_hi, ct, ct_lo, ct_hi = payload
    ax.text(0.05, yy, name, transform=lab, ha="left", va="center", fontsize=9.5, color=TEXT)
    for (e, l, h), dy, face in [(oriented(name, ex, ex_lo, ex_hi), +OFF, color),     # exercise: filled
                                (oriented(name, ct, ct_lo, ct_hi), -OFF, "white")]:  # control: open
        ax.errorbar(e, yy + dy, xerr=[[e - l], [h - e]], fmt="o", color=color, ecolor=color,
                    elinewidth=1.4, capsize=2.5, capthick=1.4, markersize=5.5,
                    markerfacecolor=face, markeredgecolor=color, markeredgewidth=1.2, zorder=3)

# axes styling
ax.set_yticks([])
for side in ("top", "right", "left"):
    ax.spines[side].set_visible(False)
ax.spines["bottom"].set_color(AXIS)
ax.spines["bottom"].set_linewidth(0.8)
ticks = [-0.4, -0.2, 0, 0.2, 0.4, 0.6, 0.8]
ax.set_xticks(ticks)
ax.set_xticklabels([("\u2212" if t < 0 else "") + f"{abs(t):g}" for t in ticks], fontsize=8, color=GRAY)
ax.tick_params(axis="x", colors=AXIS, labelcolor=GRAY, length=3, width=0.8)

# direction labels under the axis
tr = blended_transform_factory(ax.transData, ax.transAxes)
ax.text(-0.03, -0.115, "\u2190 worse", transform=tr, ha="right", va="top", fontsize=8.5, color=GRAY)
ax.text(0.03, -0.115, "better \u2192", transform=tr, ha="left", va="top", fontsize=8.5, color=GRAY)

# legend (bottom left, under the labels)
handles = [Line2D([0], [0], marker="o", ls="", color=GRAY, markerfacecolor=GRAY, markersize=5.5, label="Exercise"),
           Line2D([0], [0], marker="o", ls="", color=GRAY, markerfacecolor="white", markeredgewidth=1.2,
                  markersize=5.5, label="Control")]
fig.legend(handles=handles, loc="lower left", bbox_to_anchor=(0.01, 0.175 if SHOW_NOTE else 0.04),
           ncol=2, frameon=False, fontsize=8.5, handletextpad=0.3, columnspacing=1.0, labelcolor=TEXT)

if SHOW_NOTE:
    fig.text(0.02, 0.012,
             "z-score of change (adjusted for baseline) with 95% CI; RT sign reversed so right = better.\n"
             "Shaded = < 0.2 SD; dotted = 0.2 / 0.5 / 0.8 benchmarks (Nakagawa & Cuthill, 2007).\n"
             "Data: Mora-Gonzalez et al. (2024), Table S2. Figure created by the presenter from these data;\n"
             "not a figure from the original article.",
             ha="left", va="bottom", fontsize=7.5, style="italic", color=GRAY, linespacing=1.3)

fig.savefig(FILENAME, dpi=DPI, transparent=TRANSPARENT,
            facecolor="none" if TRANSPARENT else BG)
plt.show()

# ---------------- auto-download (goes to your Mac's Downloads folder) ----------------
try:
    from google.colab import files
    files.download(FILENAME)
except ImportError:
    print(f"Saved {FILENAME} (not running in Colab, so no auto-download).")

# Behavior results: z-score of change by group + ANCOVA comparison
# Mora-Gonzalez et al. (2024), Supplementary Table S2
# Run in Google Colab. The PNG is downloaded automatically at the end.

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Rectangle
from matplotlib.transforms import blended_transform_factory

# ---------------- settings ----------------
FILENAME    = "ancova_zscore_combined.png"
TRANSPARENT = True       # True = transparent background; False = white background
SHOW_NOTE   = True       # source note under the plot
FLIP_RT     = True       # reverse RT sign so that right = better for every outcome
DPI         = 300

# classic palette (same as the other two figures)
BG, BAND   = "#FFFFFF", "#EEEEEE"
TEXT, GRAY = "#222222", "#666666"
AXIS       = "#333333"
BLUE, ORANGE = "#0072B2", "#D55E00"      # BLUE = DNMS, ORANGE = Flanker

plt.rcParams["font.family"] = ["Calibri", "Carlito", "Liberation Sans", "DejaVu Sans"]

# ---------------- data (Table S2, values exactly as printed) ----------------
# (label, exercise z, lo, hi,  control z, lo, hi,  ANCOVA difference z (exercise − control), p)
groups = [
    ("DNMS  ·  working memory", BLUE, [
        ("Low load · RT",          -0.33, -0.60, -0.07,   -0.47, -0.76, -0.19,    0.14, ".484"),
        ("Low load · accuracy",     0.10, -0.19,  0.39,    0.18, -0.13,  0.49,   -0.08, ".712"),
        ("High load · RT",         -0.38, -0.69, -0.07,   -0.36, -0.70, -0.03,   -0.02, ".947"),
        ("High load · accuracy",   -0.01, -0.30,  0.27,    0.04, -0.26,  0.35,   -0.06, ".791"),
    ]),
    ("Flanker  ·  inhibitory control", ORANGE, [
        ("Congruent · RT",         -0.37, -0.66, -0.08,   -0.37, -0.68, -0.07,   -0.00, ".998"),
        ("Congruent · accuracy",    0.19, -0.06,  0.44,    0.10, -0.17,  0.36,    0.09, ".625"),
        ("Incongruent · RT",       -0.40, -0.65, -0.14,   -0.48, -0.75, -0.22,    0.08, ".647"),
        ("Incongruent · accuracy",  0.33,  0.19,  0.47,    0.26,  0.12,  0.40,    0.07, ".496"),
    ]),
]


def flip(label):
    return -1 if (FLIP_RT and "RT" in label) else 1


def oriented(label, est, lo, hi):
    """For RT, lower = faster = better. Flip the sign so right = better."""
    if flip(label) == -1:
        return -est, -hi, -lo
    return est, lo, hi


# ---------------- layout ----------------
rows, y = [], 0.0
for header, color, items in groups:
    rows.append(("header", y, header, color)); y -= 1
    for item in items:
        rows.append(("item", y, item, color)); y -= 1
    y -= 0.25
y_top, y_bottom = 0.95, y + 0.25 + 0.5

fig, ax = plt.subplots(figsize=(5.2, 3.85), dpi=DPI)
fig.subplots_adjust(left=0.31, right=0.76, top=0.98, bottom=0.245 if SHOW_NOTE else 0.13)
if not TRANSPARENT:
    fig.patch.set_facecolor(BG); ax.set_facecolor(BG)

XMIN, XMAX = -0.4, 0.8
ax.set_xlim(XMIN, XMAX)
ax.set_ylim(y_bottom, y_top)

first_item_y = rows[1][1]
ax.axvspan(-0.2, 0.2, color=BAND, zorder=0, lw=0)                               # < 0.2 SD = negligible
ax.plot([0, 0], [first_item_y + 0.5, y_bottom], color=GRAY, lw=0.8, zorder=1)   # zero = no change
ax.text(0, rows[0][1] + 0.55, "< 0.2 SD", ha="center", va="center", fontsize=7.5, style="italic", color=GRAY)

lab = blended_transform_factory(fig.transFigure, ax.transData)   # x in figure fraction, y in data
X_DELTA, X_P = 0.865, 0.975                                      # ANCOVA columns (figure fraction, right edge)

# shaded block behind the ANCOVA columns
y0 = fig.transFigure.inverted().transform(ax.transData.transform((0, y_bottom + 0.05)))[1]
y1 = fig.transFigure.inverted().transform(ax.transData.transform((0, rows[0][1] + 0.95)))[1]
fig.patches.append(Rectangle((0.785, y0), 0.205, y1 - y0, transform=fig.transFigure,
                             facecolor=BAND, edgecolor="none", zorder=-1))

ax.text(0.8875, rows[0][1] + 0.55, "ANCOVA", transform=lab, ha="center", va="center",
        fontsize=8.5, fontweight="bold", color=TEXT)
ax.text(X_DELTA, rows[0][1], "gap", transform=lab, ha="right", va="center", fontsize=8.5, style="italic", color=GRAY)
ax.text(X_P, rows[0][1], "p", transform=lab, ha="right", va="center", fontsize=8.5,
        style="italic", fontweight="bold", color=GRAY)

OFF = 0.18                                                       # exercise above, control below
for kind, yy, payload, color in rows:
    if kind == "header":
        ax.text(0.015, yy, payload, transform=lab, ha="left", va="center",
                fontsize=9.5, fontweight="bold", color=color)
        continue
    name, ex, ex_lo, ex_hi, ct, ct_lo, ct_hi, diff, p = payload
    ax.text(0.04, yy, name, transform=lab, ha="left", va="center", fontsize=9.5, color=TEXT)
    for (e, l, h), dy, face in [(oriented(name, ex, ex_lo, ex_hi), +OFF, color),     # exercise: filled
                                (oriented(name, ct, ct_lo, ct_hi), -OFF, "white")]:  # control: open
        ax.errorbar(e, yy + dy, xerr=[[e - l], [h - e]], fmt="o", color=color, ecolor=color,
                    elinewidth=1.4, capsize=2.5, capthick=1.4, markersize=5.5,
                    markerfacecolor=face, markeredgecolor=color, markeredgewidth=1.2, zorder=3)
    d = diff * flip(name)
    d_txt = ("+" if d > 0.004 else "\u2212" if d < -0.004 else "") + f"{abs(d):.2f}"
    ax.text(X_DELTA, yy, d_txt, transform=lab, ha="right", va="center", fontsize=9, color=TEXT)
    ax.text(X_P, yy, p, transform=lab, ha="right", va="center", fontsize=9, fontweight="bold", color=TEXT)

# axes styling
ax.set_yticks([])
for side in ("top", "right", "left"):
    ax.spines[side].set_visible(False)
ax.spines["bottom"].set_color(AXIS)
ax.spines["bottom"].set_linewidth(0.8)
ticks = [-0.4, -0.2, 0, 0.2, 0.4, 0.6, 0.8]
ax.set_xticks(ticks)
ax.set_xticklabels([("\u2212" if t < 0 else "") + f"{abs(t):g}" for t in ticks], fontsize=8, color=GRAY)
ax.tick_params(axis="x", colors=AXIS, labelcolor=GRAY, length=3, width=0.8)

tr = blended_transform_factory(ax.transData, ax.transAxes)
ax.text(-0.03, -0.105, "\u2190 worse", transform=tr, ha="right", va="top", fontsize=8.5, color=GRAY)
ax.text(0.03, -0.105, "better \u2192", transform=tr, ha="left", va="top", fontsize=8.5, color=GRAY)

handles = [Line2D([0], [0], marker="o", ls="", color=GRAY, markerfacecolor=GRAY, markersize=5.5, label="Exercise"),
           Line2D([0], [0], marker="o", ls="", color=GRAY, markerfacecolor="white", markeredgewidth=1.2,
                  markersize=5.5, label="Control")]
fig.legend(handles=handles, loc="lower left", bbox_to_anchor=(0.005, 0.135 if SHOW_NOTE else 0.02),
           ncol=2, frameon=False, fontsize=8.5, handletextpad=0.3, columnspacing=1.0, labelcolor=TEXT)

if SHOW_NOTE:
    fig.text(0.015, 0.012,
             "Dots: each group's z-score of change (adjusted for baseline) with 95% CI. Gap and p: ANCOVA\n"
             "comparison (exercise \u2212 control). RT sign reversed so right = better. Data: Mora-Gonzalez et al.\n"
             "(2024), Table S2. Figure created by the presenter from these data; not a figure from the original article.",
             ha="left", va="bottom", fontsize=7.5, style="italic", color=GRAY, linespacing=1.3)

fig.savefig(FILENAME, dpi=DPI, transparent=TRANSPARENT,
            facecolor="none" if TRANSPARENT else BG)
plt.show()

# ---------------- auto-download (goes to your Mac's Downloads folder) ----------------
try:
    from google.colab import files
    files.download(FILENAME)
except ImportError:
    print(f"Saved {FILENAME} (not running in Colab, so no auto-download).")

# Clusters that survived the t-max permutation correction
# Mora-Gonzalez et al. (2024), Table 2 (main text)
# Run in Google Colab. The PNG is downloaded automatically at the end.

import matplotlib.pyplot as plt
from matplotlib.transforms import blended_transform_factory

# ---------------- settings ----------------
FILENAME    = "tmax_results_plot.png"
TRANSPARENT = True       # True = transparent background; False = white background
SHOW_NOTE   = True       # source note under the plot
DPI         = 300

# classic palette (same as the other figures)
BG          = "#FFFFFF"
TEXT, GRAY  = "#222222", "#666666"
AXIS        = "#333333"
BLUE, ORANGE = "#0072B2", "#D55E00"      # BLUE = DNMS, ORANGE = Flanker

plt.rcParams["font.family"] = ["Calibri", "Carlito", "Liberation Sans", "DejaVu Sans"]

# ---------------- data (Table 2: peak t and cluster size k of every surviving cluster) ----------------
# Positive t = exercise group's activity rose MORE than control's; negative = rose LESS.
rows = [
    ("DNMS · after 2nd item",   "TF \u22126547 to \u22126516 ms", BLUE,
     [(3.8, 39), (3.6, 16), (3.5, 11), (3.4, 19), (3.8, 22)]),           # R BA13, 22, 31, 40, 41
    ("DNMS · before 3rd item",  "TF \u22126027 to \u22126008 ms", BLUE,
     [(3.9, 23), (3.8, 26), (3.7, 15)]),                                  # L BA9, L BA8, R BA9
    ("DNMS · during 4th item",  "TF \u22124090 to \u22124074 ms", BLUE,
     [(3.5, 17), (4.3, 18), (3.7, 13), (4.1, 14)]),                       # L BA37, 30, 22, 18
    ("DNMS · after 4th item",   "TF \u22124027 to \u22123988 ms", BLUE,
     [(2.7, 24), (3.2, 101), (2.7, 18), (2.9, 14), (2.8, 32), (3.1, 22), (2.8, 49)]),  # R BA11, 13, 20, 22, 38, 41, 47
    ("Flanker · incongruent",   "TF 508 to 528 ms", ORANGE,
     [(-4.1, 5)]),                                                        # L BA10
]

size = lambda k: 8 + 2.2 * k          # marker area grows with cluster size

# ---------------- figure ----------------
fig, ax = plt.subplots(figsize=(4.4, 2.05), dpi=DPI)
fig.subplots_adjust(left=0.37, right=0.85, top=0.97, bottom=0.40 if SHOW_NOTE else 0.22)
if not TRANSPARENT:
    fig.patch.set_facecolor(BG); ax.set_facecolor(BG)

n = len(rows)
ax.set_xlim(-5, 5)
ax.set_ylim(-0.6, n - 0.4)
ax.axvline(0, color=GRAY, lw=0.8, zorder=1)

lab = blended_transform_factory(fig.transFigure, ax.transData)
jitter = [0, 0.16, -0.16, 0.08, -0.08, 0.2, -0.2]
for i, (name, tf, color, clusters) in enumerate(rows):
    yy = n - 1 - i
    ax.axhline(yy, color="#DDDDDD", lw=0.6, zorder=0)
    ax.text(0.015, yy, name, transform=lab, ha="left", va="center", fontsize=8.5, color=color, fontweight="bold")
    for j, (t, k) in enumerate(clusters):
        ax.scatter(t, yy + jitter[j % len(jitter)], s=size(k), color=color, alpha=0.55,
                   edgecolor=color, linewidth=0.8, zorder=3)
    ax.text(0.865, yy, f"{len(clusters)} cluster" + ("s" if len(clusters) > 1 else ""), transform=lab,
            ha="left", va="center", fontsize=8, color=GRAY)

# axes styling
ax.set_yticks([])
for side in ("top", "right", "left"):
    ax.spines[side].set_visible(False)
ax.spines["bottom"].set_color(AXIS)
ax.spines["bottom"].set_linewidth(0.8)
ticks = [-4, -2, 0, 2, 4]
ax.set_xticks(ticks)
ax.set_xticklabels([("\u2212" if t < 0 else "+" if t > 0 else "") + f"{abs(t)}" for t in ticks], fontsize=8, color=GRAY)
ax.tick_params(axis="x", colors=AXIS, labelcolor=GRAY, length=3, width=0.8)

tr = blended_transform_factory(ax.transData, ax.transAxes)
ax.text(-0.2, -0.2, "\u2190 exercise rose less", transform=tr, ha="right", va="top", fontsize=7.5, color=GRAY)
ax.text(0.2, -0.2, "exercise rose more \u2192", transform=tr, ha="left", va="top", fontsize=7.5, color=GRAY)
ax.text(5.15, -0.06, "peak t", transform=tr, ha="left", va="top", fontsize=7.5, style="italic", color=GRAY)

# size legend (bottom left)
fig.text(0.015, ax.get_position().y0 - 0.075, "cluster size k:", ha="left", va="center", fontsize=7.5, color=GRAY)
for x, k in [(0.205, 5), (0.255, 25), (0.315, 100)]:
    fig.add_artist(plt.Line2D([x], [ax.get_position().y0 - 0.075], marker="o", ls="", color=GRAY, alpha=0.55,
                              markersize=(size(k)) ** 0.5, transform=fig.transFigure))
    fig.text(x, ax.get_position().y0 - 0.165, str(k), ha="center", va="center", fontsize=7, color=GRAY)

if SHOW_NOTE:
    fig.text(0.015, 0.012,
             "Each dot = one brain cluster that survived t-max correction (peak t; size = cluster size k).\n"
             "Data: Mora-Gonzalez et al. (2024), Table 2. Figure created by the presenter from these data;\n"
             "not a figure from the original article.",
             ha="left", va="bottom", fontsize=7, style="italic", color=GRAY, linespacing=1.3)

fig.savefig(FILENAME, dpi=DPI, transparent=TRANSPARENT,
            facecolor="none" if TRANSPARENT else BG)
plt.show()

# ---------------- auto-download (goes to your Mac's Downloads folder) ----------------
try:
    from google.colab import files
    files.download(FILENAME)
except ImportError:
    print(f"Saved {FILENAME} (not running in Colab, so no auto-download).")

# Power check: chance of detecting a group difference with n = 33 vs. 28 (DNMS analysed sample)
# Sample sizes from Mora-Gonzalez et al. (2024). Power calculation by the presenter.
# Run in Google Colab. The PNG is downloaded automatically at the end.

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy.optimize import brentq

# ---------------- settings ----------------
FILENAME    = "power_curve_plot.png"
TRANSPARENT = True       # True = transparent background; False = white background
SHOW_NOTE   = True       # source note under the plot
SHOW_ANCOVA = False      # True = add a lighter curve showing ANCOVA power if pre-post r = R_PREPOST
R_PREPOST   = 0.6
N1, N2      = 33, 28     # exercise, control (DNMS)
ALPHA       = 0.05
DPI         = 300

# classic palette (same as the other figures)
BG          = "#FFFFFF"
TEXT, GRAY  = "#222222", "#666666"
AXIS        = "#333333"
GRID        = "#E5E5E5"
BLUE, ORANGE = "#0072B2", "#D55E00"

plt.rcParams["font.family"] = ["Calibri", "Carlito", "Liberation Sans", "DejaVu Sans"]


# ---------------- power of a two-sided, two-sample t-test ----------------
def power(d, n1=N1, n2=N2, alpha=ALPHA):
    df = n1 + n2 - 2
    ncp = d * np.sqrt(n1 * n2 / (n1 + n2))            # noncentrality parameter
    tc = stats.t.ppf(1 - alpha / 2, df)                # critical t
    return 1 - stats.nct.cdf(tc, df, ncp) + stats.nct.cdf(-tc, df, ncp)


d = np.linspace(0, 1.2, 241)
p = np.array([power(x) for x in d]) * 100

p_medium = power(0.5) * 100                                     # power for a medium effect
d_80 = brentq(lambda x: power(x) - 0.80, 0.1, 2)                # effect needed for 80% power
n_80 = next(n for n in range(5, 500) if power(0.5, n, n) >= 0.80)  # per-group n for 80% at d = 0.5
print(f"Power at d = 0.5: {p_medium:.1f}%   |   d for 80% power: {d_80:.2f}   |   n per group for 80% at d = 0.5: {n_80}")

# ---------------- figure ----------------
fig, ax = plt.subplots(figsize=(4.4, 2.75), dpi=DPI)
fig.subplots_adjust(left=0.13, right=0.97, top=0.95, bottom=0.33 if SHOW_NOTE else 0.18)
if not TRANSPARENT:
    fig.patch.set_facecolor(BG); ax.set_facecolor(BG)

ax.set_xlim(0, 1.2)
ax.set_ylim(0, 100)
ax.set_yticks(range(0, 101, 20))
ax.set_yticklabels([f"{v}%" for v in range(0, 101, 20)], fontsize=8, color=GRAY)
ax.set_xticks(np.arange(0, 1.21, 0.2))
ax.set_xticklabels([f"{v:.1f}" for v in np.arange(0, 1.21, 0.2)], fontsize=8, color=GRAY)
ax.grid(axis="y", color=GRID, lw=0.7)
ax.set_axisbelow(True)
for side in ("top", "right"):
    ax.spines[side].set_visible(False)
for side in ("left", "bottom"):
    ax.spines[side].set_color(AXIS); ax.spines[side].set_linewidth(0.8)
ax.tick_params(colors=AXIS, labelcolor=GRAY, length=3, width=0.8)
ax.set_xlabel("True effect size (Cohen's d)", fontsize=8.5, color=GRAY)
ax.set_ylabel("Power", fontsize=8.5, color=GRAY)

# 80% target
ax.axhline(80, color=ORANGE, lw=1.2, ls=(0, (4, 3)))
ax.text(0.02, 82, "80% target", fontsize=8, color=ORANGE, va="bottom")

# optional ANCOVA curve (error variance shrinks by 1 - r^2, so d acts like d / sqrt(1 - r^2))
if SHOW_ANCOVA:
    p_anc = np.array([power(x / np.sqrt(1 - R_PREPOST ** 2)) for x in d]) * 100
    ax.plot(d, p_anc, color=BLUE, lw=1.4, alpha=0.4, ls="--")
    ax.text(0.47, 88, f"with ANCOVA\n(if pre\u2013post r = {R_PREPOST})", fontsize=7.5, color=BLUE, alpha=0.7,
            ha="right", va="center")

# main curve
ax.plot(d, p, color=BLUE, lw=2.4)

# marker: medium effect
ax.plot([0.5, 0.5], [0, p_medium], color=GRAY, lw=0.8, ls=(0, (1, 2)))
ax.plot([0, 0.5], [p_medium, p_medium], color=GRAY, lw=0.8, ls=(0, (1, 2)))
ax.scatter([0.5], [p_medium], s=40, color=BLUE, edgecolor="white", linewidth=1, zorder=4)
ax.annotate(f"d = 0.5 (medium)\n\u2192 only {p_medium:.0f}% power", xy=(0.5, p_medium), xytext=(0.6, 30),
            fontsize=8.5, color=TEXT, fontweight="bold", ha="left", va="center",
            arrowprops=dict(arrowstyle="-", color=GRAY, lw=0.8))

# marker: 80% reached
ax.plot([d_80, d_80], [0, 80], color=GRAY, lw=0.8, ls=(0, (1, 2)))
ax.scatter([d_80], [80], s=40, color=ORANGE, edgecolor="white", linewidth=1, zorder=4)
ax.annotate(f"80% only at d \u2248 {d_80:.2f}", xy=(d_80, 80), xytext=(0.86, 62),
            fontsize=8.5, color=TEXT, ha="left", va="center",
            arrowprops=dict(arrowstyle="-", color=GRAY, lw=0.8))

if SHOW_NOTE:
    fig.text(0.02, 0.012,
             f"Power of a two-sided two-sample t-test (\u03b1 = {ALPHA}), n = {N1} vs. {N2} (DNMS analysed sample).\n"
             f"80% power at d = 0.5 would need ~{n_80} children per group. Sample sizes: Mora-Gonzalez et al. (2024).\n"
             "Figure created by the presenter (own power calculation); not a figure from the original article.",
             ha="left", va="bottom", fontsize=7, style="italic", color=GRAY, linespacing=1.3)

fig.savefig(FILENAME, dpi=DPI, transparent=TRANSPARENT,
            facecolor="none" if TRANSPARENT else BG)
plt.show()

# ---------------- auto-download (goes to your Mac's Downloads folder) ----------------
try:
    from google.colab import files
    files.download(FILENAME)
except ImportError:
    print(f"Saved {FILENAME} (not running in Colab, so no auto-download).")